-- setting leader key to <Space>
vim.api.nvim_set_keymap('n', '<Space>', '<NOP>', {noremap=true, silent=true})
vim.g.mapleader = ' '


-- config

-- Better indenting
vim.api.nvim_set_keymap('v', '<', '<gv', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '>', '>gv', {noremap=true, silent=true})

-- alias for 'escape' to NORMAL from INSERT

vim.api.nvim_set_keymap('i', 'klk', '<Esc>', {noremap=true, silent=true})

--insert stuff
vim.api.nvim_set_keymap('n', '<Leader>ic', 'r!<right>', {noremap=true, silent=true})

-- select whole word
vim.api.nvim_set_keymap('n', ',w', 'viw', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', ',W', 'viW', {noremap=true, silent=true})

-- Explore
vim.api.nvim_set_keymap('n', '<Leader>.', ':Sex!<CR>', {noremap=true, silent=true})


-- Move selected line / block of text in visual mode
-- shift + k to move up
-- shift + j to move down
vim.api.nvim_set_keymap('x', 'K', ":move '<-2<CR>gv-gv", {noremap=true, silent=true})
vim.api.nvim_set_keymap('x', 'J', ":move '>+1<CR>gv-gv", {noremap=true, silent=true})

-- move lines using 'Alt', vscode-like
vim.api.nvim_set_keymap('x', '<M-Up>', ":move '<-2<CR>gv-gv", {noremap=true, silent=true})
vim.api.nvim_set_keymap('x', '<M-Down>', ":move '>+1<CR>gv-gv", {noremap=true, silent=true})

-- close brackets
vim.api.nvim_set_keymap('i', "(", "()<left>", {noremap=true, silent=true})
vim.api.nvim_set_keymap('i', "{", "{}<left>", {noremap=true, silent=true})
vim.api.nvim_set_keymap('i', "[", "[]<left>", {noremap=true, silent=true})
vim.api.nvim_set_keymap('i', "'", "''<left>", {noremap=true, silent=true})

-- xsel commands
vim.api.nvim_set_keymap('n', '<Leader>avv', '"+p', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acc', 'V"+y', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axx', 'V"+d', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avv', '"+p', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acc', '"+y', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axx', '"+d', {noremap=true, silent=true})

vim.api.nvim_set_keymap('n', '<Leader>acq', 'V"qy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acw', 'V"wy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>ace', 'V"ey', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acr', 'V"ry', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>act', 'V"ty', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acy', 'V"yy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acu', 'V"uy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>aci', 'V"iy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>aco', 'V"oy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acp', 'V"py', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>aca', 'V"ay', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acs', 'V"sy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acd', 'V"dy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acf', 'V"fy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acg', 'V"gy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>ach', 'V"hy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acj', 'V"jy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>ack', 'V"ky', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acl', 'V"ly', {noremap=true, silent=true})

vim.api.nvim_set_keymap('n', '<Leader>acQ', 'V"Qy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acW', 'V"Wy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acE', 'V"Ey', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acR', 'V"Ry', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acT', 'V"Ty', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acY', 'V"Yy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acU', 'V"Uy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acI', 'V"Iy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acO', 'V"Oy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acP', 'V"Py', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acA', 'V"Ay', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acS', 'V"Sy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acD', 'V"Dy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acF', 'V"Fy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acG', 'V"Gy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acH', 'V"Hy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acJ', 'V"Jy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acK', 'V"Ky', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>acL', 'V"Ly', {noremap=true, silent=true})

vim.api.nvim_set_keymap('v', '<Leader>acq', '"qy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acw', '"wy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>ace', '"ey', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acr', '"ry', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>act', '"ty', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acy', '"yy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acu', '"uy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>aci', '"iy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>aco', '"oy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acp', '"py', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>aca', '"ay', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acs', '"sy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acd', '"dy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acf', '"fy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acg', '"gy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>ach', '"hy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acj', '"jy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>ack', '"ky', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acl', '"ly', {noremap=true, silent=true})

vim.api.nvim_set_keymap('v', '<Leader>acQ', '"Qy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acW', '"Wy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acE', '"Ey', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acR', '"Ry', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acT', '"Ty', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acY', '"Yy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acU', '"Uy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acI', '"Iy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acO', '"Oy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acP', '"Py', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acA', '"Ay', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acS', '"Sy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acD', '"Dy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acF', '"Fy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acG', '"Gy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acH', '"Hy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acJ', '"Jy', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acK', '"Ky', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>acL', '"Ly', {noremap=true, silent=true})

vim.api.nvim_set_keymap('n', '<Leader>axq', 'V"qd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axw', 'V"wd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axe', 'V"ed', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axr', 'V"rd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axt', 'V"td', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axy', 'V"yd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axu', 'V"ud', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axi', 'V"id', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axo', 'V"od', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axp', 'V"pd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axa', 'V"ad', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axs', 'V"sd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axd', 'V"dd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axf', 'V"fd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axg', 'V"gd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axh', 'V"hd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axj', 'V"jd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axk', 'V"kd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axl', 'V"ld', {noremap=true, silent=true})

vim.api.nvim_set_keymap('n', '<Leader>axQ', 'V"Qd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axW', 'V"Wd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axE', 'V"Ed', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axR', 'V"Rd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axT', 'V"Td', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axY', 'V"Yd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axU', 'V"Ud', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axI', 'V"Id', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axO', 'V"Od', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axP', 'V"Pd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axA', 'V"Ad', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axS', 'V"Sd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axD', 'V"Dd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axF', 'V"Fd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axG', 'V"Gd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axH', 'V"Hd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axJ', 'V"Jd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axK', 'V"Kd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>axL', 'V"Ld', {noremap=true, silent=true})

vim.api.nvim_set_keymap('v', '<Leader>axq', '"qd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axw', '"wd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axe', '"ed', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axr', '"rd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axt', '"td', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axy', '"yd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axu', '"ud', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axi', '"id', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axo', '"od', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axp', '"pd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axa', '"ad', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axs', '"sd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axd', '"dd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axf', '"fd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axg', '"gd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axh', '"hd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axj', '"jd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axk', '"kd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axl', '"ld', {noremap=true, silent=true})

vim.api.nvim_set_keymap('v', '<Leader>axQ', '"Qd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axW', '"Wd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axE', '"Ed', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axR', '"Rd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axT', '"Td', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axY', '"Yd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axU', '"Ud', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axI', '"Id', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axO', '"Od', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axP', '"Pd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axA', '"Ad', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axS', '"Sd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axD', '"Dd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axF', '"Fd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axG', '"Gd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axH', '"Hd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axJ', '"Jd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axK', '"Kd', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>axL', '"Ld', {noremap=true, silent=true})

vim.api.nvim_set_keymap('n', '<Leader>avq', '"qp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avw', '"wp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>ave', '"ep', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avr', '"rp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avt', '"tp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avy', '"yp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avu', '"up', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avi', '"ip', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avo', '"op', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avp', '"pp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>ava', '"ap', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avs', '"sp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avd', '"dp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avf', '"fp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avg', '"gp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avh', '"hp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avj', '"jp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avk', '"kp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avl', '"lp', {noremap=true, silent=true})

vim.api.nvim_set_keymap('n', '<Leader>avQ', '"Qp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avW', '"Wp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avE', '"Ep', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avR', '"Rp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avT', '"Tp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avY', '"Yp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avU', '"Up', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avI', '"Ip', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avO', '"Op', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avP', '"Pp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avA', '"Ap', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avS', '"Sp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avD', '"Dp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avF', '"Fp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avG', '"Gp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avH', '"Hp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avJ', '"Jp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avK', '"Kp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('n', '<Leader>avL', '"Lp', {noremap=true, silent=true})

vim.api.nvim_set_keymap('v', '<Leader>avq', '"qp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avw', '"wp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>ave', '"ep', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avr', '"rp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avt', '"tp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avy', '"yp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avu', '"up', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avi', '"ip', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avo', '"op', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avp', '"pp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>ava', '"ap', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avs', '"sp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avd', '"dp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avf', '"fp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avg', '"gp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avh', '"hp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avj', '"jp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avk', '"kp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avl', '"lp', {noremap=true, silent=true})

vim.api.nvim_set_keymap('v', '<Leader>avQ', '"Qp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avW', '"Wp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avE', '"Ep', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avR', '"Rp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avT', '"Tp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avY', '"Yp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avU', '"Up', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avI', '"Ip', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avO', '"Op', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avP', '"Pp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avA', '"Ap', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avS', '"Sp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avD', '"Dp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avF', '"Fp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avG', '"Gp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avH', '"Hp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avJ', '"Jp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avK', '"Kp', {noremap=true, silent=true})
vim.api.nvim_set_keymap('v', '<Leader>avL', '"Lp', {noremap=true, silent=true})



-- -- b - buffer
-- vim.api.nvim_set_keymap('n', '<Leader>b1', ':b1<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>b2', ':b2<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>bB', ':Telescope buffers<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>bd', ':bd<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>bf', ':bfirst<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>bk', ':bd<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>bl', ':blast<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>bn', ':bnext<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>bp', ':bprevious<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>bt', '<C-^>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>b?', ':Telescope buffers<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>b]', ':bnext<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>b[', ':bprevious<CR>', {noremap=true, silent=true})
-- 
-- 
-- -- e - edit
-- vim.api.nvim_set_keymap('n', '<Leader>ee', ':vs $HOME/.config/nvim/init.lua<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>ef', ':vs $HOME/.config/nvim/lua/functions.lua<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>ek', ':vs $HOME/.config/nvim/lua/keybindings.lua<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>em', ':vs $HOME/.config/nvim/lua/mappings.lua<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>ep', ':vs $HOME/.config/nvim/lua/plugins.lua<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>es', ':vs $HOME/.config/nvim/lua/settings.lua<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>et', ':vs $HOME/.config/nvim/lua/temp.lua<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>ew', ':vs $HOME/.config/nvim/vimscript/plug-config/which-key.vim<CR>', {noremap=true, silent=true})
-- 
-- 
-- -- f - file
-- vim.api.nvim_set_keymap('n', '<Leader>ff', ':Sex!<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>fP', ':vs $HOME/.config/nvim/<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>fs', ':update<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>fz', ':Goyo<CR>', {noremap=true, silent=true})
-- 
-- 
-- -- g - git
-- vim.api.nvim_set_keymap('n', '<Leader>gb', ':Telescope git_branches<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>gc', ':Telescope git_commits<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>gf', ':Telescope git_files<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>gg', ':Telescope git_status<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>gs', ':Telescope git_status<CR>', {noremap=true, silent=true})
-- 
-- 
-- -- h - help
-- vim.api.nvim_set_keymap('n', '<Leader>hl', ':help :lua<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>ht', ':Telescope colorscheme<CR>', {noremap=true, silent=true})
-- 
-- 
-- -- i - insert
-- 
-- 
-- -- l - lsp
-- vim.api.nvim_set_keymap('n', '<Leader>la', ':Lspsaga code_action<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>lA', ':Lspsaga range_code_action<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>ld', ':Telescope lsp_document_diagnostics<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>lD', ':Telescope lsp_workspace_diagnostics<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>lf', ':LspFormatting<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>lH', ':Lspsaga signature_help<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>lI', ':LspInfo<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>lv', ':LspVirtualTextToggle<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>ll', ':Lspsaga lsp_finder<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>lL', ':Lspsaga show_line_diagnostics<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>lo', ':Vista!!<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>lp', ':Lspsaga preview_definition<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>lq', ':Telescope quickfix<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>lr', ':Lspsaga rename<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>lT', ':LspTypeDefinition<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>lx', ':cclose<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>ls', ':Telescope lsp_document_symbols<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>lS', ':Telescope lsp_workspace_symbols<CR>', {noremap=true, silent=true})
-- 
-- 
-- -- o -open
-- vim.api.nvim_set_keymap('n', '<Leader>oe', ':NvimTreeToggle<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>or', ':RnvimrToggle<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>ot', ':FloatermToggle<CR>', {noremap=true, silent=true})
-- 
-- 
-- -- q - quit
-- vim.api.nvim_set_keymap('n', '<Leader>qq', ':q<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>qa', ':qa<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>qr', ':luafile $HOME/.config/nvim/init.lua<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>qu', ':update<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>qw', ':wq<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>q!', ':q!<CR>', {noremap=true, silent=true})
-- 
-- 
-- -- r - reload
-- vim.api.nvim_set_keymap('n', '<Leader>rr', ':luafile $HOME/.config/nvim/init.lua<CR>', {noremap=true, silent=true})
-- 
-- 
-- -- s - search
-- 
-- 
-- -- t - toggle
-- vim.api.nvim_set_keymap('n', '<Leader>tb', '<C-^>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>te', ':NvimTreeToggle<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>th', ':set hls!<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>ts', ':set spell!<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>tt', ':FloatermToggle<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>tz', ':Goyo<CR>', {noremap=true, silent=true})
-- 
-- 
-- -- w - window
-- vim.api.nvim_set_keymap('n', '<Leader>wb', '<C-^>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>wc', '<C-W>c', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>wh', '<C-W>h', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>wj', '<C-W>j', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>wk', '<C-W>k', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>wl', '<C-W>l', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>wH', '<C-W>5<', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>wJ', ':resize +5<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>wK', ':resize -5<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>wL', '<C-W>5>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>ws', '<C-W>s', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>wv', '<C-W>v', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>ww', '<C-W>w', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>w-', '<C-W>s', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>w|', '<C-W>v', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>w=', '<C-W>=', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>w2', '<C-W>v', {noremap=true, silent=true})
-- 
-- 
-- -- z - Telescope
-- vim.api.nvim_set_keymap('n', '<Leader>zb', ':Telescope buffers<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>zC', ':Telescope colorscheme<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>zc', ':Telescope git_commits<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>zf', ':Telescope find_files<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>zh', ':Telescope command_history<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>zl', ':Telescope Lines<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>zm', ':Telescope marks<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>zr', ':Telescope registers<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>zt', ':Telescope tags<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>zv', ':Telescope commands<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>zw', ':Telescope file_browser<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>zz', ':Telescope live_grep<CR>', {noremap=true, silent=true})
-- vim.api.nvim_set_keymap('n', '<Leader>zZ', ':Telescope grep_string<CR>', {noremap=true, silent=true})
-- 
-- 
